### PR TITLE
Add Logux Status demo page

### LINKED ISSUE #9: Integration tests
We need webpack to build single page to test all Logux Status features in real.

### PR DESCRIPTION
**Pull request by kuznetsov0209**
Resolve #9 

Demo Logux Status features: log, attention, confirm, favicon
Add npm script to run demo by webpack-dev-server
Add npm script to build demo page into one html file with js bundle included

### CODE REVIEW

**Comment by kuznetsov0209** [comment]
Deployed it on GitHub Pages https://kuznetsov0209.github.io/logux-status/

**Comment by ai** [comment]
Great! Few fixes:

1. Could you use Logux logo from `https://cdn.rawgit.com/logux/logux/master/logo.svg`?
2. Could you move `demo/` to `test/integration/`. It will be like integration tests :D.

Also, why to we need `demo/build.js`. To inline JS to HTML? Maybe there is a webpack plugin for it?

**Comment by kuznetsov0209** [comment]
Found some weird behavior of connection instance: it can't be established after disconnect:
1. call `client.sync.connection.connect()` — connected
2. call `client.sync.connection.disconnect()` — disconnected
3. call `client.sync.connection.connect()` — nothing happened

**Comment by ai** [comment]
@kuznetsov0209 maybe it is Logux issue. Don’t worry, I will fix Logux on this page :).

**Comment by kuznetsov0209** [comment]
> Also, why to we need demo/build.js. To inline JS to HTML? Maybe there is a webpack plugin for it?
I use it to inline JS to HTML. Didn't find any solution better :(

**Comment by ai** [comment]
@kuznetsov0209 OK, `build.js`is fine. I will accept pull request only in Monday evening (need to finish my slides :( ). Maybe you could fix merge conflict before it?

**Comment by kuznetsov0209** [comment]
@ai ok

**Comment by ai** [comment]
Thanks! I marked [task](http://cultofmartians.com/tasks/logux-status-integration.html) as solved by you.

**Comment by ai** [comment]
I found a way to inline JS into HTML without extra JS file:

1. [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin)
2. [html-webpack-inline-source-plugin](https://github.com/DustinJackson/html-webpack-inline-source-plugin)

**Comment by ai** [comment]
Oops, you accedently put very big `test/integration/index.html` into repo :(

**Comment by kuznetsov0209** [comment]
> I found a way to inline JS into HTML without extra JS file

I thought my google skills were better... 😄  
I'll create another PR to apply this plugin

> Any build files should not be part of repository.

I put it only to deploy on github pages (https://jacobthemyth.gitbooks.io/tiy-gvl-fee-2015-august/content/notes/production-and-deployment/webpack-gh-pages.html)

> Also strange to put build/ into project root. Because it is always better to keep everything inside test/demo/ directory.
Emm... Could you please clarify this point? Is it about webpack output option or something else?

**Comment by ai** [comment]
Don't worry, I anyway updates demo page style right now and will add this plugin. Anyway you did great work and finish most of work.

**Comment by ai** [comment]
Great work! I published you page: https://logux.github.io/logux-status/

**Comment by kuznetsov0209** [comment]
Awesome! My first step into Open Source!

**Comment by ai** [comment]
@kuznetsov0209 wow, great first pull request! Better than my [first one](https://github.com/hagenburger/lemonade/pull/13).

What is your Twitter and VK accounts? I need it for announce.

**Comment by ai** [comment]
Also your face will be on React London https://slides.com/ai/logux

**Comment by kuznetsov0209** [comment]
😄 Thanks! [Twitter](https://twitter.com/kuznetsov0209) & [VK](https://vk.com/alexey_kuznetsow)

**Pull request merged**
