### PR TITLE
feature(confirm): Confirm close on unsent actions

### PR DESCRIPTION
**Pull request by barbagrigia**
Issues #1

### CODE REVIEW

**Comment by ai** [comment]
You need to fix Travis CI error.

**Comment by ai** [comment]
1. You need to show warning on `sending` state too. Because user could close tab in the middle of synchronization.
2. Logux Client saves unsynchronized actions too IndexedDB. So they will not be lost on tab closing. We need to fix default text.
3. You forget to add docs to `README.md`.

**Comment by barbagrigia** [comment]
1. 👌 No problem. I made in accordance with [p.5](http://cultofmartians.com/tasks/logux-status-confirm.html) "... in the presence of unsent events ..." But about `sending` too thought 😉 
2. I suggest this default text: `Not all data will be synchronize with the server if you leave the page.`
3. 😕

**Comment by ai** [comment]
Text is good. Waiting for commits and we ready to merge 👍.

**Comment by ai** [comment]
Great. And I need your VK and Twitter accounts for announce.

**Comment by barbagrigia** [comment]
Few minutes until I will be add docs to README.md ✋

**Comment by ai** [comment]
Dun’t forget your VK and Twitter accounts names.

**Comment by barbagrigia** [comment]
Added docs to README.md (sorry for my poor English)
[@barba_grigia](https://twitter.com/barba_grigia)
In VK I almost there.

**Pull request merged**
