### PR TITLE
feature(favicon): Change favicon on sync state

### PR DESCRIPTION
**Pull request by andrewmnlv**
#2

### CODE REVIEW

**Comment by ai** [comment]
1. What if user pass only `error` and `online`? It is good that you thought about it — code will use `online` for offline. But “online” term could not be used for offline ;). So I suggest to rename `online` to `default`.
2. What if page doesn’t have `link[rel~="icon"]`? For example, page uses default address `/favicon.ico`? In this case you need to add `<link>`.
3. You need a test that `offline` icon doesn’t override `error` (`error` event could be emitted before disconnection, but I am not sure).
4. You doesn’t describe why offline favicon is best practice for UX :D. The main reason: user should always be sure, that she/he have latest updates. If pages goes offline, we must notify user, that data could be outdated. By using favicon we could notify user even if she/he is in other tab.
5. I think you will like this problem :D. How developer will make a favicon? In real world designers are always unavailable or ignore strange requests from developers (like ”draw a favicon for Logux” — “what Logux?”) This is why we should give a recommendation for creating a favicon. For offline icon developers could make a black-and-white version and make it a little lighter. For errror developers could put a red dot to favicon.

**Comment by andrewmnlv** [comment]
"what Logux?" nice :laughing:

About `default`. It is reserved name. May be we should use `normal` or something else?
Then we avoid, for example `favicon({ default: icoLink, error, offline })` in ES-2015. What do you think?

**Comment by andrewmnlv** [comment]
1,2,3 - updated; 4,5 - just copied your notes, text messages isn't for me 😬

**Comment by ai** [comment]
Sure, let’s replace to `normal` if `default` could produce some problem.

**Comment by andrewmnlv** [comment]
renamed to normal

**Comment by ai** [comment]
Great! Good work :+1:

**Pull request merged**
