### PR TITLE
feature(attention): Highlight tabs on error

### PR DESCRIPTION
**Pull request by andrewmnlv**
Issue #3

### CODE REVIEW

**Comment by ai** [comment]
Great, thanks! Here is few things to fix:

1. `sync instanceof BaseSync` works not perfect in JS, because of CommonJS isolation. As result, `logux-status` and user app may use different versions of `logux-sync` and `BaseSync` will be different. So, `sync = sync.sync ? sync.sync : sync` will be OK.
2. It is always better to use toThrowError with error message regexp. Because it could be a syntax error, or some other error.
3. In `checks sync property as instance of BaseSync` test we need to check what sync was really used. You can check `sync.emitter.events` for your listeners.
4. In `returns unbind function` you should check that function really unbind listeners. Just copy `title` test here.

**Comment by ai** [comment]
And I will need your Twitter and VK account for announce

**Comment by andrewmnlv** [comment]
@ai one question for first point: use only `sync = sync.sync ? sync.sync : sync` and remove check that sync or sync property is an instance of BaseSync, right?

**Comment by ai** [comment]
Yeap, remove check. Unfortunately it can be done in node.js in proper way.

**Comment by andrewmnlv** [comment]
@ai up

**Comment by ai** [comment]
Great. I will accept it after few hours.

I will need your Twitter and VK account for announce.

**Comment by andrewmnlv** [comment]
[twitter](https://twitter.com/andrewmnlv)
[vk](https://vk.com/andrewmnlv)

**Pull request merged**
