### PR TITLE
Add screenshots for all features

### PR DESCRIPTION
**Pull request by frsv**
https://github.com/logux/logux-status/issues/11

### CODE REVIEW

**Comment by ai** [comment]
1. I think all screenshots should be taken in Chrome as most popular browser.
2. `attention` screenshot has no tab highlight. Maybe Firefox didn’t do it?
3. `confirm` screenshot cropped non-symmetrically. 
4. `favicon` could be showed in one screenshot.
5. Favicon for `favicon` should be more beautiful.
6. `log` screenshot has unnecessary line on the right.
7. Maybe we should fix #9 first and show screenshot from this test page?

**Comment by frsv** [comment]
2. Actually, I didn't notice tab highlighting even in Chrome. I'll recheck it
4. Screenshot should be inlined or should contain three rows?
5. I'm just wondering how to make it 'more beautiful' :) I had seen `favicon` amplifr preview before – https://www.youtube.com/watch?v=gfxyCmeXGZc, so maybe should I use these icons? I'm not designer, actually.
7. Well,  maybe you're right. But users won't see the screenshots until they copy the repo. On the test page we can show these features live.

**Comment by ai** [comment]
2. So we definitely need a integration test before screenshots, to fix all features.
3. I mean `confirm` screenshot should not contain other website on background.
4. Sure, you can use Amplifr’s: [normal](https://amplifr.com/favicon.ico), [offline](https://amplifr.com/static/offline.ico), [error](https://amplifr.com/static/error.ico). Every frontender is a designers ;). Try to learn more about design, it will make your code better, because you will unsderstand what and why you do.
5. You can put images in `gh-pages` brunch to use it in `README.md`. This is how I put Logux logo there.

**Comment by ai** [comment]
Logux Status got demo page, so you can make this PR again :)

**Comment by ai** [comment]
I will close this PR so you can open new one

**Pull request closed without merging**
