### PR TITLE
Add badge

### PR DESCRIPTION
**Pull request by LeoVS09**
Notification, when connection failed or data can't synchronize
disconnected

### CODE REVIEW

**Comment by ai** [comment]
Did you see that we have already 3 PR about it? 😉

**Comment by ai** [comment]
Your test page is good. Could you send separated PR for new demo page?

**Comment by LeoVS09** [comment]
I did not notice this, but you can delete task from http://cultofmartians.com/
This is new main page #25

**Comment by ai** [comment]
I “cherry-picked” few good commits. But main author of task will be @iffjey, because his work cover more cases and file size is smaller.

**Pull request closed without merging**
