### PR TITLE
feature(log): Logger

### PR DESCRIPTION
**Pull request by andrewmnlv**
#4

### CODE REVIEW

**Comment by ai** [comment]
1. All Logux lines should contains `Logux` word. Because Logux will be used with Redux. And Redux have own logger too. So developer should understood where this `console.log` came from.
2. `Sync: error code` it for machines, not human. For example, errors have good human readable description `error.description`. Same this other messages. Image that you creating a help for junior developer with only 3 months development experience.
3. Should we allow developers to disable some messages type? How `redux-logger` deal with it?

**Comment by ai** [comment]
Also, don't forget about docs in README.md. Docs is the most important part of open source (even more than code).

**Comment by andrewmnlv** [comment]
Thanks! Just wanted to ask about format of messages, but forgot
3. It's a good idea. I think we could add an optional second argument `log(sync, option)` to have possibility configuring logger. I've never worked with `react`, especially with `redux-logger` =) Probably I will look `redux-logger` tomorrow

**Comment by ai** [comment]
We could add options later, but right now we should make text better.

For example, `Logux was connected to ws://127.0.0.1:31337`. Or `Logux server send error: TImeout` instead of `Logux Sync: clientError`.

**Comment by ai** [comment]
Think about console as a UX. Try to explain what happen. Try to understand (or ask question for me) why developer will need this message (like `connect` is needed to understand what server URL is used).

**Comment by ai** [comment]
Yeap. Much better. But we need full action in message (just send it as second argument, so DevTools will show nice preset).

Also using `localNodeId` isn't the best way. Action could be created on server and then synchronized to client. Use `meta.id[1]` to get real action creator.

**Comment by andrewmnlv** [comment]
I need help with connect. If it `ClientSync`, then we could detect url by `sync.connection.connection.url`- looks bad. And what about other cases?

**Comment by ai** [comment]
You don't need to set `localNodeId` everywhere. Imagine real usage — you will have same nodeId again and again in your log. As a developer, will you happy with this messages?

Ask yourself, what information do you need for each event. For example, in `connect` event server URL will be useful.

So stop to write code, let's think first. Write what information we should print for each event.

**Comment by andrewmnlv** [comment]
No, it will be annoying

- Logux was connected to `url`.
- Logux changed synchronization state to `state`.
- Logux `remoteNodeId` sent `type` error (`description`).
- Logux `localNodeId`? received `type` error (`description`).
- Logux added new action `type` to log. `action` `meta`?

**Comment by ai** [comment]
Don’t write exactly text. It blocks your mind on current implementation.

Clean your brain. Forget about current implementation and code.

Ask yourself what will you need on every event? What is a context? What is a possible issues, that developer will try to fix?

And write `event → data` list.

**Comment by andrewmnlv** [comment]
connect - who, where and when connected
state - previous and new states. as addition - event, which provided new state
error - detailed description and place where it happened
add - who added this log and detailed info about this action

**Comment by andrewmnlv** [comment]
last chance =D

- Logux connected to `url`.
- Logus state is `state`.
- Logux `meta.id[1]` added `type` action. `action`
- Logux server sent error `description`. `remoteNodeId`

**Comment by ai** [comment]
All this messages are not related with your message https://github.com/logux/logux-status/pull/6#issuecomment-279817653

* Logux `localNodeId` are connected to `remoteNodeId` at `url` (you told who).
* Logux change state to `state` (you told about prev state, but I think developer have messages history for it).
* `meta.id[1]` added `type` action to Logux: action (If `meta.id[1] === localNodeId` write “`type` action was added …”).
* Logux server sent error: `description` (we display server error in connected message)
* Logux error: `description` (local errors should have shorter prefix)

**Comment by ai** [comment]
Also don’t forget about new `clean` log event: https://github.com/logux/logux-core#clean

**Comment by ai** [comment]
Also we need `meta` in `add` event. It contains many important b data for debug.

**Comment by andrewmnlv** [comment]
Thanks! I'm just hopeless

And what prefix for local errors do you mean?

**Comment by ai** [comment]
> Thanks! I'm just hopeless

Cult of Martians tasks should train you something, right ;).

> And what prefix for local errors do you mean?

Just `Logux error:`

**Comment by andrewmnlv** [comment]
Cult of Martians is a really good thing!:+1:

**Comment by ai** [comment]
😄 Waiting for messages update and options to disable messages types. And we are ready to merge.

**Comment by ai** [comment]
@andrewmnlv do not do merge command ;).

Undo last commit:

```sh
git reset HEAD^
git push origin feature/log
```

Then do rebase:

```sh
git checkout master
git pull git@github.com:logux/logux-status.git master
git checkout feature/log
git rebase master
```

It will keep commits log cleaner and protect from merge hell.

**Comment by andrewmnlv** [comment]
@ai can we refresh dependencies of CI? seem like it use old logux-core without `clean` event...

**Comment by ai** [comment]
Great! Tiny thing to fix — `clean` could be done only by current log. So there is no need to `meta.id[1] + ' clean ' + action.type + ' action from Logux:`.

**Comment by ai** [comment]
Done, I reset a cache.

**Comment by ai** [comment]
Also error should be printed by `console.error`, not `console.log`.

**Comment by ai** [comment]
Never mind, I will fix it by myself. Anyway you spend so many time. Thanks, good work.

**Comment by andrewmnlv** [comment]
already add console.error and push it =)

**Comment by andrewmnlv** [comment]
Thank you for your patience :smile:

**Pull request merged**
